apiVersion: v1
kind: ConfigMap
metadata:
  name: agri-config
  namespace: ml-service
data:
  POSTGRES_HOST: "host.minikube.internal"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "agriculture-vision"
  POSTGRES_USER: "developer"
  POSTGRES_PASSWORD: "developer"
  DATABASE_URL: "postgresql+asyncpg://developer:developer@host.minikube.internal:5432/agriculture-vision"
  DATABASE_SYNC_URL: "postgresql://developer:developer@host.minikube.internal:5432/agriculture-vision"
  REDIS_URL: "redis://host.minikube.internal:6379/0"
  CELERY_BROKER_URL: "redis://host.minikube.internal:6379/0"
  S3_ENDPOINT_URL: "http://host.minikube.internal:9000"
  S3_BUCKET: "agrovision"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"