apiVersion: apps/v1
kind: Deployment
metadata:
  name: agriculture-vision-frontend
  namespace: ml-service
  labels:
    app: agri-frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: agri-frontend
  template:
    metadata:
      labels:
        app: agri-frontend
    spec:
      containers:
        - name: frontend
          image: FRONTEND_IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: agri-frontend-service
  namespace: ml-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081 # Выделяем отдельный порт для фронтенда
      name: http
  selector:
    app: agri-frontend